@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

AddressBook *-right-> "1" UniquePersonList
AddressBook *-right-> "1" UniqueSubjectList
UniqueSubjectList -[hidden]down- UniquePersonList
UniqueSubjectList -[hidden]down- UniquePersonList

UniqueSubjectList -right-> "*" Subject
UniquePersonList -right-> Person

Person -up-> "*" Subject

Person *--> Name
Person *--> Phone
Person *--> Email
Person *--> Address
Person *--> NextLesson
Person *--> PayStatus
@enduml
