@startuml
hide circle
skinparam classAttributeIconSize 0

Class "{abstract}\nCommand" as Command {
  +execute(Model): CommandResult {abstract}
}
Class FilterDateCommand {
  +COMMAND_WORD: String
  +MESSAGE_SUCCESS: String
  +MESSAGE_USAGE: String
  -predicate: NextLessonEqualsDatePredicate
  +execute(Model): CommandResult
}
Class CommandException

FilterDateCommand -up-|> Command
Command ..> CommandException: throws >
FilterDateCommand .right.> CommandException: throws >
@enduml
